classdef uiblockingalert < handle
    
    methods ( Access = public )
        
        function obj = uiblockingalert( f, message, title )
            
            [ ~ ] = uiconfirm( ...
                f, ...
                message, ...
                title, ...
                'options', { 'OK' }, ...
                'icon', 'error', ...
                'defaultoption', 1, ...
                'canceloption', 1 ...
                );
            
        end
        
    end
    
end

